### ISSUE TITLE
Injecting own recipe as a yaml file

### ISSUE THREAD

**Issue by kddiji** [rhythmictech/terraform-aws-imagebuilder-component-shell#7]
I would like to inject a yaml file with many commands as a component of this project. I would appreciate any pointers on how to do that . The yaml file is something like the  `centoshardening`

```
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: CISBenchmarkHardening
        action: ExecuteBash
        inputs:
          commands:

            # §1.1
            - echo "install cramfs /bin/true" > /etc/modprobe.d/cramfs.conf
            - echo "install vfat /bin/true" > /etc/modprobe.d/vfat.conf
            - etc 
```

**Comment by sblack4** [comment]
The commands in the component get `yamlencode`ed so just list them: https://github.com/rhythmictech/terraform-aws-imagebuilder-component-shell/blob/main/component.yml.tpl#L13

don't forget to escape the double quotes 

```tf
module "test_shell_component" {
  source  = "rhythmictech/imagebuilder-component-shell/aws"
  version = "~> 0.1.0"

  component_version = "1.0.0"
  description       = "Testing component"
  name              = "testing-component"
  commands          = ["echo \"install cramfs /bin/true\" > /etc/modprobe.d/cramfs.conf", "etc"]
  tags              = local.tags
}

```

**Comment by kddiji** [comment]
Thanks for the response. The problem with that is that I have 2 components `yml` files and each has ~ 200 lines of commands to hardened a centos OS which means I would have to hard code that way `"echo \"install cramfs /bin/true\" > /etc/modprobe.d/cramfs.conf", "command", "command", "etc"]`? Is there a way to just have those 2 yaml files seating somewhere in the repo and pass them in the `component.yml.tpl` and `variables.tf`.

**Comment by sblack4** [comment]
I see the use-case. that should be as easy as adding a new variable and a ternary for [`local.data` ](https://github.com/rhythmictech/terraform-aws-imagebuilder-component-shell/blob/main/main.tf#L4)
it looks like the same thing is possible by using [`var.data_uri`](https://github.com/rhythmictech/terraform-aws-imagebuilder-component-shell/blob/main/variables.tf#L29) but you'd have to upload your `yml` files to S3 first. 

If you make the PR adding the new variable named `data_override` or something and change the local to use the contents of the new variable instead of the templatefile if the `data_override` is specified I'll approve and merge it

**Comment by kddiji** [comment]
@sblack4  thanks for the feedback that was helpful. The actual commands in my yaml are defined as below:
```
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: Test
        action: ExecuteBash
        inputs:
          commands:

            # §1.1
            - echo "install cramfs /bin/true" > /etc/modprobe.d/cramfs.conf
            - echo "install vfat /bin/true" > /etc/modprobe.d/vfat.conf
            - echo "install squashfs /bin/true" > /etc/modprobe.d/squashfs.conf
            - echo "install udf /bin/true" > /etc/modprobe.d/udf.conf
            - echo "install usb-storage /bin/true" > /etc/modprobe.d/usb-storage.conf
 ```
and I decided to define them as indicated in the module `list(string)`.  See below
```
variable "commands" {
#  default     = ["echo test component"]
  description = "List of strings. Each string is a shell command"
  type        = list(string)
  default     = [
    "echo 'install cramfs /bin/true' > /etc/modprobe.d/cramfs.conf",
    "echo 'install vfat /bin/true' > /etc/modprobe.d/vfat.conf",
    "echo 'install squashfs /bin/true' > /etc/modprobe.d/squashfs.conf",
    "echo 'install udf /bin/true' > /etc/modprobe.d/udf.conf",
    "echo 'install usb-storage /bin/true' > /etc/modprobe.d/usb-storage.conf"  
  ]
}
```
Crossing fingers that each command line will work as expected as a `shell` command even though I am using a single quote inside the code block. Last question I have in the EC2 image builder console there is a function to specify the OS versions that this component is compatible with which is CentOs linux 8 for my stacks. Is there a way to specify it in this project? Thanks in advance really appreciate your feedback.
