### ISSUE TITLE
Requesting to make this compatible with Windows Powershell by using a new var

### ISSUE THREAD

**Issue by Vermyndax** [rhythmictech/terraform-aws-imagebuilder-component-shell#9]
**Is your feature request related to a problem? Please describe.**
The component.yml.tpl file hardcodes the word "ExecuteBash," which will fail on Windows components. It appears that allowing this to be set to "ExecutePowershell" this can be made Windows-compatible in the same module.

**Describe the solution you'd like**
Perhaps a detection on the OS var that if it's set to "Windows" then flip the ExecuteBash in the tpl to ExecutePowershell.

**Describe alternatives you've considered**
Maybe just a variable with a default of ExecuteBash that can be overriden.

**Additional context**
Here's a Hello World example of a Windows component that uses Powershell:

```
name: HelloWorldTestingDocument
description: This is hello world testing document.
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: HelloWorldStep
        action: ExecutePowerShell
        inputs:
          commands:
            - echo "Hello World! Build."

  - name: validate
    steps:
      - name: HelloWorldStep
        action: ExecutePowerShell
        inputs:
          commands:
            - echo "Hello World! Validate."

  - name: test
    steps:
      - name: HelloWorldStep
        action: ExecutePowerShell
        inputs:
          commands:
            - echo "Hello World! Test."
```
